[platformio]
src_dir = test/build
default_envs = d1_mini

[env]
lib_extra_dirs = .
lib_deps =
  links2004/WebSockets @ 2.3.4
upload_speed = 1500000
monitor_speed = 115200
; build_flags = -D WEBSOCKET_DISABLED=false

[env:build-esp32]
platform = espressif32
board = esp32dev
framework = arduino

[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino

[env:d1_mini]
platform = espressif8266
framework = arduino
board = d1_mini
upload_speed = 921600
